# Generated by Django 4.2.9 on 2024-01-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_slug_thread_postid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='replyID',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='postID',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='threadname',
            new_name='title',
        ),
    ]
